version: '3.8'

services:
  web:
    build: .
    container_name: barberia_flask_app
    expose:
      - "80"
    volumes:
      - /app/__pycache__
      - barberking_uploads:/app/app/static/uploads
    environment:
      - TZ=${TZ}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_DB_HOST=${EVOLUTION_DB_HOST}
      - EVOLUTION_DB_PORT=${EVOLUTION_DB_PORT}
      - EVOLUTION_DB_USER=${EVOLUTION_DB_USER}
      - EVOLUTION_DB_PASSWORD=${EVOLUTION_DB_PASSWORD}
      - EVOLUTION_DB_NAME=${EVOLUTION_DB_NAME}
      - EVOLUTION_SERVER_URL=${EVOLUTION_SERVER_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PREFIX=${REDIS_PREFIX}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH}
      - ADMIN_RESET=${ADMIN_RESET}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - DEFAULT_INSTANCE=${DEFAULT_INSTANCE}
    command: gunicorn --bind 0.0.0.0:80 --workers 2 --threads 2 --timeout 60 run:app
    depends_on: {}
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true

volumes:
  barberking_uploads: